# Generated by Django 3.1.5 on 2021-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0002_auto_20210131_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
