# Generated by Django 3.1.5 on 2021-01-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0003_productmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
