# Generated by Django 3.1.5 on 2021-01-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0005_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
