# Generated by Django 3.1.5 on 2021-02-04 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0009_auto_20210204_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 4, 17, 56, 6, 795675))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MStore.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MStore.productmodel')),
            ],
        ),
    ]
